phalcon.lo: /root/lnmp7_centos6/src/phalcon/phalcon.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/lnmp7_centos6/src/phalcon $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/lnmp7_centos6/src/phalcon/phalcon.c -o phalcon.lo 
kernel/main.lo: /root/lnmp7_centos6/src/phalcon/kernel/main.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/lnmp7_centos6/src/phalcon $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/lnmp7_centos6/src/phalcon/kernel/main.c -o kernel/main.lo 
kernel/memory.lo: /root/lnmp7_centos6/src/phalcon/kernel/memory.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/lnmp7_centos6/src/phalcon $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/lnmp7_centos6/src/phalcon/kernel/memory.c -o kernel/memory.lo 
kernel/exception.lo: /root/lnmp7_centos6/src/phalcon/kernel/exception.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/lnmp7_centos6/src/phalcon $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/lnmp7_centos6/src/phalcon/kernel/exception.c -o kernel/exception.lo 
kernel/debug.lo: /root/lnmp7_centos6/src/phalcon/kernel/debug.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/lnmp7_centos6/src/phalcon $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/lnmp7_centos6/src/phalcon/kernel/debug.c -o kernel/debug.lo 
kernel/backtrace.lo: /root/lnmp7_centos6/src/phalcon/kernel/backtrace.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/lnmp7_centos6/src/phalcon $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/lnmp7_centos6/src/phalcon/kernel/backtrace.c -o kernel/backtrace.lo 
kernel/object.lo: /root/lnmp7_centos6/src/phalcon/kernel/object.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/lnmp7_centos6/src/phalcon $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/lnmp7_centos6/src/phalcon/kernel/object.c -o kernel/object.lo 
kernel/array.lo: /root/lnmp7_centos6/src/phalcon/kernel/array.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/lnmp7_centos6/src/phalcon $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/lnmp7_centos6/src/phalcon/kernel/array.c -o kernel/array.lo 
kernel/string.lo: /root/lnmp7_centos6/src/phalcon/kernel/string.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/lnmp7_centos6/src/phalcon $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/lnmp7_centos6/src/phalcon/kernel/string.c -o kernel/string.lo 
kernel/fcall.lo: /root/lnmp7_centos6/src/phalcon/kernel/fcall.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/lnmp7_centos6/src/phalcon $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/lnmp7_centos6/src/phalcon/kernel/fcall.c -o kernel/fcall.lo 
kernel/require.lo: /root/lnmp7_centos6/src/phalcon/kernel/require.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/lnmp7_centos6/src/phalcon $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/lnmp7_centos6/src/phalcon/kernel/require.c -o kernel/require.lo 
kernel/file.lo: /root/lnmp7_centos6/src/phalcon/kernel/file.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/lnmp7_centos6/src/phalcon $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/lnmp7_centos6/src/phalcon/kernel/file.c -o kernel/file.lo 
kernel/operators.lo: /root/lnmp7_centos6/src/phalcon/kernel/operators.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/lnmp7_centos6/src/phalcon $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/lnmp7_centos6/src/phalcon/kernel/operators.c -o kernel/operators.lo 
kernel/math.lo: /root/lnmp7_centos6/src/phalcon/kernel/math.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/lnmp7_centos6/src/phalcon $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/lnmp7_centos6/src/phalcon/kernel/math.c -o kernel/math.lo 
kernel/concat.lo: /root/lnmp7_centos6/src/phalcon/kernel/concat.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/lnmp7_centos6/src/phalcon $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/lnmp7_centos6/src/phalcon/kernel/concat.c -o kernel/concat.lo 
kernel/variables.lo: /root/lnmp7_centos6/src/phalcon/kernel/variables.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/lnmp7_centos6/src/phalcon $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/lnmp7_centos6/src/phalcon/kernel/variables.c -o kernel/variables.lo 
kernel/filter.lo: /root/lnmp7_centos6/src/phalcon/kernel/filter.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/lnmp7_centos6/src/phalcon $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/lnmp7_centos6/src/phalcon/kernel/filter.c -o kernel/filter.lo 
kernel/iterator.lo: /root/lnmp7_centos6/src/phalcon/kernel/iterator.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/lnmp7_centos6/src/phalcon $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/lnmp7_centos6/src/phalcon/kernel/iterator.c -o kernel/iterator.lo 
kernel/time.lo: /root/lnmp7_centos6/src/phalcon/kernel/time.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/lnmp7_centos6/src/phalcon $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/lnmp7_centos6/src/phalcon/kernel/time.c -o kernel/time.lo 
kernel/exit.lo: /root/lnmp7_centos6/src/phalcon/kernel/exit.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/lnmp7_centos6/src/phalcon $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/lnmp7_centos6/src/phalcon/kernel/exit.c -o kernel/exit.lo 
phalcon/db/adapterinterface.lo: /root/lnmp7_centos6/src/phalcon/phalcon/db/adapterinterface.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/lnmp7_centos6/src/phalcon $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/lnmp7_centos6/src/phalcon/phalcon/db/adapterinterface.zep.c -o phalcon/db/adapterinterface.lo 
phalcon/events/eventsawareinterface.lo: /root/lnmp7_centos6/src/phalcon/phalcon/events/eventsawareinterface.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/lnmp7_centos6/src/phalcon $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/lnmp7_centos6/src/phalcon/phalcon/events/eventsawareinterface.zep.c -o phalcon/events/eventsawareinterface.lo 
phalcon/db/adapter.lo: /root/lnmp7_centos6/src/phalcon/phalcon/db/adapter.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/lnmp7_centos6/src/phalcon $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/lnmp7_centos6/src/phalcon/phalcon/db/adapter.zep.c -o phalcon/db/adapter.lo 
phalcon/db/dialectinterface.lo: /root/lnmp7_centos6/src/phalcon/phalcon/db/dialectinterface.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/lnmp7_centos6/src/phalcon $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/lnmp7_centos6/src/phalcon/phalcon/db/dialectinterface.zep.c -o phalcon/db/dialectinterface.lo 
phalcon/exception.lo: /root/lnmp7_centos6/src/phalcon/phalcon/exception.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/lnmp7_centos6/src/phalcon $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/lnmp7_centos6/src/phalcon/phalcon/exception.zep.c -o phalcon/exception.lo 
phalcon/db/adapter/pdo.lo: /root/lnmp7_centos6/src/phalcon/phalcon/db/adapter/pdo.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/lnmp7_centos6/src/phalcon $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/lnmp7_centos6/src/phalcon/phalcon/db/adapter/pdo.zep.c -o phalcon/db/adapter/pdo.lo 
phalcon/db/columninterface.lo: /root/lnmp7_centos6/src/phalcon/phalcon/db/columninterface.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/lnmp7_centos6/src/phalcon $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/lnmp7_centos6/src/phalcon/phalcon/db/columninterface.zep.c -o phalcon/db/columninterface.lo 
phalcon/db/dialect.lo: /root/lnmp7_centos6/src/phalcon/phalcon/db/dialect.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/lnmp7_centos6/src/phalcon $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/lnmp7_centos6/src/phalcon/phalcon/db/dialect.zep.c -o phalcon/db/dialect.lo 
phalcon/db/indexinterface.lo: /root/lnmp7_centos6/src/phalcon/phalcon/db/indexinterface.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/lnmp7_centos6/src/phalcon $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/lnmp7_centos6/src/phalcon/phalcon/db/indexinterface.zep.c -o phalcon/db/indexinterface.lo 
phalcon/db/referenceinterface.lo: /root/lnmp7_centos6/src/phalcon/phalcon/db/referenceinterface.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/lnmp7_centos6/src/phalcon $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/lnmp7_centos6/src/phalcon/phalcon/db/referenceinterface.zep.c -o phalcon/db/referenceinterface.lo 
phalcon/db/resultinterface.lo: /root/lnmp7_centos6/src/phalcon/phalcon/db/resultinterface.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/lnmp7_centos6/src/phalcon $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/lnmp7_centos6/src/phalcon/phalcon/db/resultinterface.zep.c -o phalcon/db/resultinterface.lo 
phalcon/events/eventinterface.lo: /root/lnmp7_centos6/src/phalcon/phalcon/events/eventinterface.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/lnmp7_centos6/src/phalcon $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/lnmp7_centos6/src/phalcon/phalcon/events/eventinterface.zep.c -o phalcon/events/eventinterface.lo 
phalcon/events/managerinterface.lo: /root/lnmp7_centos6/src/phalcon/phalcon/events/managerinterface.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/lnmp7_centos6/src/phalcon $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/lnmp7_centos6/src/phalcon/phalcon/events/managerinterface.zep.c -o phalcon/events/managerinterface.lo 
phalcon/db.lo: /root/lnmp7_centos6/src/phalcon/phalcon/db.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/lnmp7_centos6/src/phalcon $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/lnmp7_centos6/src/phalcon/phalcon/db.zep.c -o phalcon/db.lo 
phalcon/db/adapter/pdo/mysql.lo: /root/lnmp7_centos6/src/phalcon/phalcon/db/adapter/pdo/mysql.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/lnmp7_centos6/src/phalcon $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/lnmp7_centos6/src/phalcon/phalcon/db/adapter/pdo/mysql.zep.c -o phalcon/db/adapter/pdo/mysql.lo 
phalcon/db/column.lo: /root/lnmp7_centos6/src/phalcon/phalcon/db/column.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/lnmp7_centos6/src/phalcon $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/lnmp7_centos6/src/phalcon/phalcon/db/column.zep.c -o phalcon/db/column.lo 
phalcon/db/dialect/mysql.lo: /root/lnmp7_centos6/src/phalcon/phalcon/db/dialect/mysql.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/lnmp7_centos6/src/phalcon $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/lnmp7_centos6/src/phalcon/phalcon/db/dialect/mysql.zep.c -o phalcon/db/dialect/mysql.lo 
phalcon/db/exception.lo: /root/lnmp7_centos6/src/phalcon/phalcon/db/exception.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/lnmp7_centos6/src/phalcon $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/lnmp7_centos6/src/phalcon/phalcon/db/exception.zep.c -o phalcon/db/exception.lo 
phalcon/db/index.lo: /root/lnmp7_centos6/src/phalcon/phalcon/db/index.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/lnmp7_centos6/src/phalcon $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/lnmp7_centos6/src/phalcon/phalcon/db/index.zep.c -o phalcon/db/index.lo 
phalcon/db/profiler.lo: /root/lnmp7_centos6/src/phalcon/phalcon/db/profiler.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/lnmp7_centos6/src/phalcon $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/lnmp7_centos6/src/phalcon/phalcon/db/profiler.zep.c -o phalcon/db/profiler.lo 
phalcon/db/profiler/item.lo: /root/lnmp7_centos6/src/phalcon/phalcon/db/profiler/item.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/lnmp7_centos6/src/phalcon $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/lnmp7_centos6/src/phalcon/phalcon/db/profiler/item.zep.c -o phalcon/db/profiler/item.lo 
phalcon/db/rawvalue.lo: /root/lnmp7_centos6/src/phalcon/phalcon/db/rawvalue.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/lnmp7_centos6/src/phalcon $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/lnmp7_centos6/src/phalcon/phalcon/db/rawvalue.zep.c -o phalcon/db/rawvalue.lo 
phalcon/db/reference.lo: /root/lnmp7_centos6/src/phalcon/phalcon/db/reference.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/lnmp7_centos6/src/phalcon $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/lnmp7_centos6/src/phalcon/phalcon/db/reference.zep.c -o phalcon/db/reference.lo 
phalcon/db/result/pdo.lo: /root/lnmp7_centos6/src/phalcon/phalcon/db/result/pdo.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/lnmp7_centos6/src/phalcon $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/lnmp7_centos6/src/phalcon/phalcon/db/result/pdo.zep.c -o phalcon/db/result/pdo.lo 
phalcon/events/event.lo: /root/lnmp7_centos6/src/phalcon/phalcon/events/event.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/lnmp7_centos6/src/phalcon $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/lnmp7_centos6/src/phalcon/phalcon/events/event.zep.c -o phalcon/events/event.lo 
phalcon/events/exception.lo: /root/lnmp7_centos6/src/phalcon/phalcon/events/exception.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/lnmp7_centos6/src/phalcon $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/lnmp7_centos6/src/phalcon/phalcon/events/exception.zep.c -o phalcon/events/exception.lo 
phalcon/events/manager.lo: /root/lnmp7_centos6/src/phalcon/phalcon/events/manager.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/lnmp7_centos6/src/phalcon $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/lnmp7_centos6/src/phalcon/phalcon/events/manager.zep.c -o phalcon/events/manager.lo 
phalcon/kernel.lo: /root/lnmp7_centos6/src/phalcon/phalcon/kernel.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/lnmp7_centos6/src/phalcon $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/lnmp7_centos6/src/phalcon/phalcon/kernel.zep.c -o phalcon/kernel.lo 
$(phplibdir)/phalcon.la: ./phalcon.la
	$(LIBTOOL) --mode=install cp ./phalcon.la $(phplibdir)

./phalcon.la: $(shared_objects_phalcon) $(PHALCON_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_phalcon) $(PHALCON_SHARED_LIBADD)

